rm(list=ls())
install.packages("MASS")
install.packages("car")
install.packages("pscl")
install.packages("ggplot2")
install.packages("boot")
install.packages("AER")
install.packages("fitdistrplus")
install.packages("performance")
install.packages("randomForest")
install.packages("VGAM")
install.packages("DT")
install.packages("car")
library(MASS)
library(car)
library(pscl)
library(ggplot2)
library(boot)
library(AER)
library(fitdistrplus)
library(performance)
library(randomForest)
library(VGAM)
library(DT) 
library(car)
data =read.delim("clipboard")
str(data)
model = lm(Y~., data = data)
vif(model)

#Regresi Poisson
m<- glm(Y~X1+X2+X3+X4+X5+X6, family="poisson", data=data)
summary(m)
check_overdispersion(m)

#Regresi binomial negatif
m2<- glm.nb(Y~X1+X2+X3+X4+X5+X6, data=data)
summary(m2)

#Membandingkan model
model_performance(m,metrics = "all")
model_performance(m2,metrics = "all")
